version: '3.9'

services:
  app:
    build:
      context: .
      args:
        # Set development mode when running via docker-compose
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      # Map local volume (dir) app to Docker app dir do avoid rebuilding docker image everytime
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"